const KEY='allurBusinessLiveV1';
const services=['Grafički dizajn','Web dizajn','Brending','Vođenje društvenih mreža','Štampa','Foto / video','Edukacije','Ostalo'];
const expenses=['Materijal','Štampa / kooperacija','Gorivo','Marketing','Oprema','Dostava','Režije','Porezi i doprinosi','Ostalo'];
const uid=()=>Math.random().toString(36).slice(2)+Date.now().toString(36);
const money=n=>new Intl.NumberFormat('bs-BA',{minimumFractionDigits:2,maximumFractionDigits:2}).format(Number(n||0))+' KM';
let db=JSON.parse(localStorage.getItem(KEY)||'null')||{clients:[{id:uid(),name:'BestTech'},{id:uid(),name:'Cordoba'},{id:uid(),name:'Hotel Krone'}],income:[],expenses:[],invoices:[]};
function save(){localStorage.setItem(KEY,JSON.stringify(db));render();}
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const today=()=>new Date().toISOString().slice(0,10);
$('#todayLabel').textContent=new Intl.DateTimeFormat('bs-BA',{day:'2-digit',month:'long',year:'numeric'}).format(new Date());
$$('.nav-item').forEach(b=>b.onclick=()=>{const p=b.dataset.page;$$('.nav-item').forEach(x=>x.classList.toggle('active',x===b));$$('.page').forEach(x=>x.classList.remove('active'));$('#page-'+p).classList.add('active');const labels={dashboard:'Dashboard',prihodi:'Prihodi',rashodi:'Rashodi',fakture:'Fakture',klijenti:'Klijenti',kpr:'KPR',izvjestaji:'Izvještaji'};$('#pageTitle').textContent=labels[p];});
function modal(title,html,onSubmit){$('#modalTitle').textContent=title;$('#modalSubtitle').textContent='Allur Business';$('#modalBody').innerHTML=html;$('#modal').classList.remove('hidden');const f=$('#modalBody form');if(f)f.onsubmit=e=>{e.preventDefault();onSubmit(new FormData(f));$('#modal').classList.add('hidden');};}
document.addEventListener('click',e=>{if(e.target.matches('[data-close]'))$('#modal').classList.add('hidden')});
function addTransaction(kind){const cats=kind==='income'?services:expenses;modal(kind==='income'?'Dodaj prihod':'Dodaj rashod',`<form class="form-grid"><label>Datum<input name="date" type="date" value="${today()}" required></label><label>${kind==='income'?'Klijent':'Dobavljač'}<input name="party" required></label><label class="wide">Opis<input name="description" required></label><label>Kategorija<select name="category">${cats.map(x=>`<option>${x}</option>`).join('')}</select></label><label>Način plaćanja<select name="payment"><option>Banka</option><option>Gotovina</option><option>Kartica</option></select></label><label>Iznos (KM)<input name="amount" type="number" step="0.01" min="0" required></label><label>Broj dokumenta<input name="documentNo"></label><div class="form-actions wide"><button class="primary-btn">Sačuvaj</button></div></form>`,f=>{db[kind==='income'?'income':'expenses'].push({id:uid(),date:f.get('date'),party:f.get('party'),description:f.get('description'),category:f.get('category'),payment:f.get('payment'),amount:Number(f.get('amount')),documentNo:f.get('documentNo')});save();});}
$('#addIncomeBtn').onclick=()=>addTransaction('income');$('#addExpenseBtn').onclick=()=>addTransaction('expense');$('#quickAddBtn').onclick=()=>addTransaction('income');
$('#addClientBtn').onclick=()=>modal('Novi klijent',`<form class="form-grid"><label class="wide">Naziv klijenta<input name="name" required></label><label>Email<input name="email" type="email"></label><label>Telefon<input name="phone"></label><label class="wide">Adresa<input name="address"></label><div class="form-actions wide"><button class="primary-btn">Sačuvaj</button></div></form>`,f=>{db.clients.push({id:uid(),name:f.get('name'),email:f.get('email'),phone:f.get('phone'),address:f.get('address')});save();});
function del(type,id){if(confirm('Obrisati unos?')){db[type]=db[type].filter(x=>x.id!==id);save();}} window.del=del;
function render(){const now=new Date(),m=now.getMonth(),y=now.getFullYear();const mi=db.income.filter(x=>{let d=new Date(x.date);return d.getMonth()===m&&d.getFullYear()===y}),me=db.expenses.filter(x=>{let d=new Date(x.date);return d.getMonth()===m&&d.getFullYear()===y});const si=mi.reduce((s,x)=>s+x.amount,0),se=me.reduce((s,x)=>s+x.amount,0);$('#statIncome').textContent=money(si);$('#statExpense').textContent=money(se);$('#statProfit').textContent=money(si-se);$('#statIncomeCount').textContent=mi.length+' unosa';$('#statExpenseCount').textContent=me.length+' unosa';$('#statUnpaid').textContent=money(0);$('#statUnpaidCount').textContent='0 faktura';
$('#incomeTable').innerHTML=db.income.length?[...db.income].reverse().map(x=>`<tr><td>${x.date}</td><td>${esc(x.party)}</td><td>${esc(x.description)}</td><td>${esc(x.category)}</td><td>${esc(x.payment)}</td><td class="right amount-income">${money(x.amount)}</td><td><button class="action-btn" onclick="del('income','${x.id}')">Obriši</button></td></tr>`).join(''):'<tr><td colspan="7" class="empty">Nema prihoda.</td></tr>';
$('#expenseTable').innerHTML=db.expenses.length?[...db.expenses].reverse().map(x=>`<tr><td>${x.date}</td><td>${esc(x.party)}</td><td>${esc(x.description)}</td><td>${esc(x.category)}</td><td>${esc(x.payment)}</td><td class="right amount-expense">${money(x.amount)}</td><td><button class="action-btn" onclick="del('expenses','${x.id}')">Obriši</button></td></tr>`).join(''):'<tr><td colspan="7" class="empty">Nema rashoda.</td></tr>';
$('#clientGrid').innerHTML=db.clients.map(c=>`<article class="client-card"><div class="client-card-top"><div style="display:flex;gap:11px"><div class="avatar">${esc(c.name[0])}</div><div><h4>${esc(c.name)}</h4><p>${esc(c.email||c.phone||'Klijent')}</p></div></div></div></article>`).join('');
let saldo=0,rows=[...db.income.map(x=>({...x,k:'i'})),...db.expenses.map(x=>({...x,k:'e'}))].sort((a,b)=>a.date.localeCompare(b.date));$('#kprTable').innerHTML=rows.length?rows.map((x,i)=>{saldo+=x.k==='i'?x.amount:-x.amount;return `<tr><td>${i+1}</td><td>${x.date}</td><td>${esc(x.documentNo||'—')}</td><td>${esc(x.description)}</td><td class="right">${x.k==='i'?money(x.amount):'—'}</td><td class="right">${x.k==='e'?money(x.amount):'—'}</td><td class="right">${money(saldo)}</td></tr>`}).join(''):'<tr><td colspan="7" class="empty">KPR je prazan.</td></tr>';$('#kprFoot').innerHTML=`<tr><th colspan="4">UKUPNO</th><th class="right">${money(db.income.reduce((s,x)=>s+x.amount,0))}</th><th class="right">${money(db.expenses.reduce((s,x)=>s+x.amount,0))}</th><th class="right">${money(saldo)}</th></tr>`;
$('#recentTransactions').innerHTML=rows.length?[...rows].reverse().slice(0,6).map(x=>`<tr><td>${x.date}</td><td>${esc(x.description)}</td><td>${esc(x.category)}</td><td>${x.k==='i'?'Prihod':'Rashod'}</td><td class="right">${money(x.amount)}</td></tr>`).join(''):'<tr><td colspan="5" class="empty">Nema transakcija.</td></tr>';$('#serviceBreakdown').innerHTML='<div class="empty">Dodaj prihode za analitiku.</div>';$('#chart').innerHTML='<div class="empty" style="padding-top:90px">Grafikon će se popuniti unosom podataka.</div>';$('#invoiceSummary').innerHTML='<div class="summary-row"><span>Prototip faktura</span><strong>sljedeća faza</strong></div>';$('#invoiceTable').innerHTML='<tr><td colspan="7" class="empty">Fakture dodajemo u sljedećoj iteraciji.</td></tr>';$('#yearIncome').textContent=money(db.income.reduce((s,x)=>s+x.amount,0));$('#yearExpense').textContent=money(db.expenses.reduce((s,x)=>s+x.amount,0));$('#yearProfit').textContent=money(db.income.reduce((s,x)=>s+x.amount,0)-db.expenses.reduce((s,x)=>s+x.amount,0));$('#yearClients').textContent=db.clients.length;$('#topClients').innerHTML='<div class="empty">Podaci se računaju iz prihoda.</div>';$('#expenseBreakdown').innerHTML='<div class="empty">Dodaj rashode za analitiku.</div>';}
render();
