/* Allur Business – FBiH poslovne knjige upgrade */
(function(){
  // ---------- migrations ----------
  db.profile = db.profile || {ownerName:'',businessName:'ALLUR',jmb:'',jib:'',address:'',activity:'',vatRegistered:false,vatNumber:''};
  db.assets = db.assets || [];
  db.epo = db.epo || [];
  db.kp = db.kp || [];
  db.clients = (db.clients||[]).map(c=>({id:c.id||uid(),name:c.name||'',contact:c.contact||'',email:c.email||'',phone:c.phone||'',idNumber:c.idNumber||'',vatNumber:c.vatNumber||'',address:c.address||''}));
  db.income = (db.income||[]).map(x=>({...x,clientId:x.clientId||'',vat:Number(x.vat||0),incomeMode:x.incomeMode||(x.payment==='Gotovina'?'cash':x.payment==='Banka'?'bank':'other')}));
  db.expenses = (db.expenses||[]).map(x=>({...x,vat:Number(x.vat||0),expenseClass:x.expenseClass||(x.category==='Porezi i doprinosi'?'contrib':x.category==='Materijal'?'material':'other')}));
  localStorage.setItem(KEY,JSON.stringify(db));

  const css=`
    .books-tabs{display:flex;gap:8px;flex-wrap:wrap;margin-bottom:16px}.book-tab{border:1px solid #dfe4ea;background:#fff;padding:9px 13px;border-radius:9px;cursor:pointer;font-weight:700}.book-tab.active{background:#111827;color:#fff;border-color:#111827}
    .book-pane{display:none}.book-pane.active{display:block}.law-note{background:#f8fafc;border:1px solid #e2e8f0;border-left:4px solid #111827;border-radius:10px;padding:12px 14px;margin:0 0 16px;font-size:13px;line-height:1.5;color:#475569}
    .profile-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}.profile-grid label{display:flex;flex-direction:column;gap:6px;font-size:12px;font-weight:700;color:#64748b}.profile-grid input,.profile-grid select{border:1px solid #dbe2ea;border-radius:9px;padding:10px;background:#fff}.wide3{grid-column:1/-1}
    .official-table{font-size:11px;min-width:1500px}.official-table th{white-space:normal;line-height:1.25;vertical-align:bottom}.official-table td{white-space:nowrap}.book-head{display:flex;justify-content:space-between;gap:15px;align-items:flex-start;margin-bottom:14px}.book-head h3{margin:0 0 4px}.book-head p{margin:0;color:#64748b;font-size:12px}.book-actions{display:flex;gap:8px;flex-wrap:wrap}.small-btn{border:1px solid #dbe2ea;background:#fff;border-radius:8px;padding:8px 10px;font-weight:700;cursor:pointer}.pdf-btn{background:#111827;color:#fff;border-color:#111827}
    .client-select{width:100%}.helper{font-size:11px;color:#94a3b8;font-weight:500}.tag{display:inline-block;padding:4px 7px;border-radius:999px;background:#f1f5f9;font-size:10px;font-weight:800;color:#475569}.book-empty{text-align:center;color:#94a3b8;padding:28px}.nowrap{white-space:nowrap}.right{text-align:right}
    @media(max-width:760px){.profile-grid{grid-template-columns:1fr}.book-head{flex-direction:column}.books-tabs{overflow:auto;flex-wrap:nowrap}.book-tab{white-space:nowrap}}
  `;
  const st=document.createElement('style');st.textContent=css;document.head.appendChild(st);

  // ---------- navigation / page ----------
  const oldKprBtn=document.querySelector('[data-page="kpr"]');
  if(oldKprBtn){ oldKprBtn.innerHTML='<span>≡</span> Poslovne knjige'; oldKprBtn.dataset.page='books'; }
  const oldKprPage=$('#page-kpr');
  if(oldKprPage){ oldKprPage.id='page-books'; oldKprPage.innerHTML=`
    <div class="books-tabs">
      <button class="book-tab active" data-book="kpr">KPR-1041</button>
      <button class="book-tab" data-book="kp">KP-1042</button>
      <button class="book-tab" data-book="pldi">PLDI-1043</button>
      <button class="book-tab" data-book="epo">EPO-1044</button>
      <button class="book-tab" data-book="profile">Podaci obrta</button>
    </div>
    <div id="book-kpr" class="book-pane active"></div><div id="book-kp" class="book-pane"></div><div id="book-pldi" class="book-pane"></div><div id="book-epo" class="book-pane"></div><div id="book-profile" class="book-pane"></div>`; }
  if(oldKprBtn){ oldKprBtn.onclick=()=>showPage('books'); }
  function showPage(p){
    $$('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.page===p));
    $$('.page').forEach(x=>x.classList.remove('active'));
    const pg=$('#page-'+p); if(pg) pg.classList.add('active');
    const labels={dashboard:'Dashboard',prihodi:'Prihodi',rashodi:'Rashodi',fakture:'Fakture',klijenti:'Klijenti',books:'Poslovne knjige FBiH',izvjestaji:'Izvještaji'};
    $('#pageTitle').textContent=labels[p]||p; $('#pageSubtitle').textContent=p==='books'?'KPR-1041 · KP-1042 · PLDI-1043 · EPO-1044':'Pregled poslovanja Allur obrta';
  }
  $$('.book-tab').forEach(b=>b.onclick=()=>{ $$('.book-tab').forEach(x=>x.classList.toggle('active',x===b)); $$('.book-pane').forEach(x=>x.classList.remove('active')); $('#book-'+b.dataset.book).classList.add('active'); });

  // ---------- clients ----------
  function clientOptions(selected=''){ return '<option value="">— Odaberi klijenta —</option>'+db.clients.map(c=>`<option value="${c.id}" ${c.id===selected?'selected':''}>${esc(c.name)}</option>`).join(''); }
  function clientName(id,fallback=''){ return (db.clients.find(c=>c.id===id)||{}).name||fallback||''; }
  $('#addClientBtn').onclick=()=>modal('Novi klijent',`<form class="form-grid"><label class="wide">Naziv klijenta<input name="name" required></label><label>Kontakt osoba<input name="contact"></label><label>Email<input name="email" type="email"></label><label>Telefon<input name="phone"></label><label>ID broj / JIB<input name="idNumber"></label><label>PDV broj<input name="vatNumber"></label><label class="wide">Adresa<input name="address"></label><div class="form-actions wide"><button type="button" class="ghost-btn" data-close>Odustani</button><button class="primary-btn">Sačuvaj klijenta</button></div></form>`,f=>{db.clients.push({id:uid(),name:f.get('name'),contact:f.get('contact'),email:f.get('email'),phone:f.get('phone'),idNumber:f.get('idNumber'),vatNumber:f.get('vatNumber'),address:f.get('address')});save();});

  // ---------- transaction form replacement ----------
  addTransaction=function(kind){
    const isIncome=kind==='income'; const cats=isIncome?services:expenses;
    modal(isIncome?'Dodaj prihod':'Dodaj rashod',`<form class="form-grid">
      <label>Datum ${isIncome?'naplate':'plaćanja'}<input name="date" type="date" value="${today()}" required><span class="helper">KPR se vodi po principu blagajne.</span></label>
      ${isIncome?`<label>Klijent<select name="clientId" class="client-select">${clientOptions()}</select><span class="helper">Klijente unosiš jednom u sekciji Klijenti.</span></label>`:`<label>Dobavljač<input name="party" required></label>`}
      <label class="wide">Opis dokumenta / poslovne promjene<input name="description" required placeholder="npr. Faktura za grafički dizajn"></label>
      <label>${isIncome?'Usluga':'Interna kategorija'}<select name="category">${cats.map(x=>`<option>${x}</option>`).join('')}</select></label>
      <label>Broj dokumenta<input name="documentNo" placeholder="npr. 12/2026" required></label>
      ${isIncome?`<label>Način naplate<select name="incomeMode"><option value="bank">Transakcijski račun</option><option value="cash">Gotovina</option><option value="other">Stvari / usluge / drugo</option></select></label>`:`<label>KPR vrsta rashoda<select name="expenseClass"><option value="material">Nabavka robe / materijala (kol.16)</option><option value="wages">Bruto plaće zaposlenika (kol.17)</option><option value="contrib">Obavezni doprinosi (kol.18)</option><option value="other">Ostali porezno priznati rashodi (kol.19)</option></select></label>`}
      <label>Iznos sa PDV-om (KM)<input name="amount" type="number" step="0.01" min="0" required></label>
      <label>PDV sadržan u iznosu (KM)<input name="vat" type="number" step="0.01" min="0" value="0"><span class="helper">0 ako nisi PDV obveznik.</span></label>
      <div class="form-actions wide"><button type="button" class="ghost-btn" data-close>Odustani</button><button class="primary-btn">Sačuvaj</button></div></form>`,f=>{
        const amount=Number(f.get('amount')),vat=Number(f.get('vat')||0); if(vat>amount){alert('PDV ne može biti veći od ukupnog iznosa.');return;}
        if(isIncome){const cid=f.get('clientId');db.income.push({id:uid(),date:f.get('date'),clientId:cid,party:clientName(cid,'Ostali kupac'),description:f.get('description'),category:f.get('category'),payment:f.get('incomeMode')==='cash'?'Gotovina':f.get('incomeMode')==='bank'?'Banka':'Ostalo',incomeMode:f.get('incomeMode'),amount,vat,documentNo:f.get('documentNo')});}
        else db.expenses.push({id:uid(),date:f.get('date'),party:f.get('party'),description:f.get('description'),category:f.get('category'),payment:'Banka',expenseClass:f.get('expenseClass'),amount,vat,documentNo:f.get('documentNo')});
        save();
      });
  };

  // ---------- data helpers ----------
  function kprRows(){ let n=0; return [...db.income.map(x=>({date:x.date,doc:x.documentNo||'',desc:x.description||'',cash:x.incomeMode==='cash'?x.amount:0,bank:x.incomeMode==='bank'?x.amount:0,otherIn:x.incomeMode==='other'?x.amount:0,inVat:x.vat||0,material:0,wages:0,contrib:0,otherExp:0,outVat:0})),...db.expenses.map(x=>({date:x.date,doc:x.documentNo||'',desc:x.description||'',cash:0,bank:0,otherIn:0,inVat:0,material:x.expenseClass==='material'?x.amount:0,wages:x.expenseClass==='wages'?x.amount:0,contrib:x.expenseClass==='contrib'?x.amount:0,otherExp:x.expenseClass==='other'?x.amount:0,outVat:x.vat||0}))].sort((a,b)=>a.date.localeCompare(b.date)).map(r=>{r.no=++n;r.totalIncome=r.cash+r.bank+r.otherIn-r.inVat;r.totalExpense=r.material+r.wages+r.contrib+r.otherExp-r.outVat;return r;}); }
  function num(n){return n?money(n):'—'}
  function total(rows,key){return rows.reduce((s,r)=>s+Number(r[key]||0),0)}
  function profileHead(code,title){const p=db.profile;return `<div class="book-head"><div><h3>${title} <span class="tag">${code}</span></h3><p>${esc(p.businessName||'ALLUR')} · ${esc(p.jib||'JIB nije unesen')} · ${esc(p.address||'Adresa nije unesena')}</p></div><div class="book-actions"><button class="small-btn pdf-btn" data-pdf="${code.toLowerCase()}">PDF export</button></div></div>`;}

  // ---------- books rendering ----------
  function renderBooks(){
    const rows=kprRows();
    $('#book-kpr').innerHTML=profileHead('KPR','Knjiga prihoda i rashoda')+`<div class="law-note"><b>KPR‑1041</b> je evidencija dnevnih i ukupnih poslovnih prihoda i rashoda. Prihodi se razvrstavaju na gotovinu, transakcijski račun i druge oblike, a rashodi na robu/materijal, bruto plaće, doprinose i ostale porezno priznate rashode. Kolone “ukupno” se automatski računaju bez sadržanog PDV-a.</div><article class="panel"><div class="table-wrap"><table class="official-table"><thead><tr><th>7<br>R.br.</th><th>8<br>Datum</th><th>9<br>Broj dokumenta</th><th>10<br>Opis dokumenta</th><th>11<br>Prihod gotovina</th><th>12<br>Prihod trans. račun</th><th>13<br>Prihod drugo</th><th>14<br>PDV u prihodima</th><th>15<br>Ukupan prihod</th><th>16<br>Roba / materijal</th><th>17<br>Bruto plaće</th><th>18<br>Doprinosi</th><th>19<br>Ostali rashodi</th><th>20<br>PDV u rashodima</th><th>21<br>Ukupni dopustivi rashodi</th></tr></thead><tbody>${rows.length?rows.map(r=>`<tr><td>${r.no}</td><td>${r.date}</td><td>${esc(r.doc)}</td><td>${esc(r.desc)}</td><td class="right">${num(r.cash)}</td><td class="right">${num(r.bank)}</td><td class="right">${num(r.otherIn)}</td><td class="right">${num(r.inVat)}</td><td class="right"><b>${num(r.totalIncome)}</b></td><td class="right">${num(r.material)}</td><td class="right">${num(r.wages)}</td><td class="right">${num(r.contrib)}</td><td class="right">${num(r.otherExp)}</td><td class="right">${num(r.outVat)}</td><td class="right"><b>${num(r.totalExpense)}</b></td></tr>`).join(''):'<tr><td colspan="15" class="book-empty">Nema evidentiranih poslovnih promjena.</td></tr>'}</tbody><tfoot><tr><th colspan="4">UKUPNO</th>${['cash','bank','otherIn','inVat','totalIncome','material','wages','contrib','otherExp','outVat','totalExpense'].map(k=>`<th class="right">${money(total(rows,k))}</th>`).join('')}</tr></tfoot></table></div></article>`;

    const kpRows=(db.kp||[]).sort((a,b)=>a.date.localeCompare(b.date));
    $('#book-kp').innerHTML=profileHead('KP','Knjiga prometa')+`<div class="law-note"><b>KP‑1042</b> je dodatna knjiga za prodaju robe na malo ili pružanje usluga građanima na više prodajnih mjesta, ako dnevni gotovinski promet za svako mjesto nije osiguran drugim propisanim evidencijama. Dnevni promet se unosi na kraju radnog dana, najkasnije prije početka sljedećeg radnog dana.</div><div class="book-actions" style="margin-bottom:12px"><button class="primary-btn" id="addKpBtn">+ Dodaj dnevni promet</button></div><article class="panel"><div class="table-wrap"><table><thead><tr><th>8 R.br.</th><th>9 Datum</th><th>10 Dokument</th><th>11 Opis</th><th class="right">12 Gotovina</th><th class="right">13 Bezgotovinski</th><th class="right">14 Ukupno</th><th></th></tr></thead><tbody>${kpRows.length?kpRows.map((r,i)=>`<tr><td>${i+1}</td><td>${r.date}</td><td>${esc(r.doc)}</td><td>${esc(r.desc)}</td><td class="right">${money(r.cash)}</td><td class="right">${money(r.bank)}</td><td class="right"><b>${money(Number(r.cash)+Number(r.bank))}</b></td><td><button class="action-btn" onclick="delBook('kp','${r.id}')">Obriši</button></td></tr>`).join(''):'<tr><td colspan="8" class="book-empty">Nema unosa u KP‑1042.</td></tr>'}</tbody></table></div></article>`;

    const assets=db.assets||[];
    $('#book-pldi').innerHTML=profileHead('PLDI','Popisna lista dugotrajne imovine')+`<div class="law-note"><b>PLDI‑1043</b> vodi se od početka obavljanja djelatnosti i služi za utvrđivanje rashoda amortizacije. Popis se sastavlja za svaku kalendarsku godinu i zaključuje sa stanjem 31. decembra.</div><div class="book-actions" style="margin-bottom:12px"><button class="primary-btn" id="addAssetBtn">+ Dodaj dugotrajnu imovinu</button></div><article class="panel"><div class="table-wrap"><table class="official-table"><thead><tr><th>8 R.br.</th><th>9 Naziv stvari/prava</th><th>10 Datum nabavke</th><th>11 Dokument</th><th class="right">12 Nabavna vrijednost</th><th class="right">13 Knjigov. vrijednost</th><th>14 Vijek trajanja</th><th>15 Stopa amort.</th><th class="right">16 Otpis</th><th class="right">17 Vrijednost na kraju</th><th></th></tr></thead><tbody>${assets.length?assets.map((a,i)=>`<tr><td>${i+1}</td><td>${esc(a.name)}</td><td>${a.date}</td><td>${esc(a.doc)}</td><td class="right">${money(a.cost)}</td><td class="right">${money(a.bookValue)}</td><td>${esc(a.life)} god.</td><td>${Number(a.rate).toFixed(2)}%</td><td class="right">${money(a.depr)}</td><td class="right"><b>${money(Math.max(0,Number(a.bookValue)-Number(a.depr)))}</b></td><td><button class="action-btn" onclick="delBook('assets','${a.id}')">Obriši</button></td></tr>`).join(''):'<tr><td colspan="11" class="book-empty">Nema unesene dugotrajne imovine.</td></tr>'}</tbody></table></div></article>`;

    const epo=db.epo||[];
    $('#book-epo').innerHTML=profileHead('EPO','Evidencija potraživanja i obaveza')+`<div class="law-note"><b>EPO‑1044</b> obuhvata izdate i primljene račune, datume i iznose naplate/uplate te vezu sa rednim brojem KPR-a. Sva potraživanja poreznog perioda moraju biti iskazana najkasnije 30 dana po isteku poreznog perioda.</div><div class="book-actions" style="margin-bottom:12px"><button class="primary-btn" id="addEpoBtn">+ Dodaj potraživanje / obavezu</button></div><article class="panel"><div class="table-wrap"><table class="official-table"><thead><tr><th>7 R.br.</th><th>8 Kupac / dobavljač</th><th>Vrsta</th><th>Broj računa</th><th>Datum računa</th><th class="right">Iznos računa</th><th>Datum naplate/uplate</th><th class="right">Naplaćeno/uplaćeno</th><th>19 R.br. KPR</th><th></th></tr></thead><tbody>${epo.length?epo.map((e,i)=>`<tr><td>${i+1}</td><td>${esc(e.party)}</td><td>${e.type==='receivable'?'Potraživanje':'Obaveza'}</td><td>${esc(e.invoiceNo)}</td><td>${e.invoiceDate}</td><td class="right">${money(e.amount)}</td><td>${e.paidDate||'—'}</td><td class="right">${money(e.paidAmount||0)}</td><td>${esc(e.kprNo||'—')}</td><td><button class="action-btn" onclick="delBook('epo','${e.id}')">Obriši</button></td></tr>`).join(''):'<tr><td colspan="10" class="book-empty">Nema unosa u EPO‑1044.</td></tr>'}</tbody></table></div></article>`;

    const p=db.profile;
    $('#book-profile').innerHTML=`<div class="book-head"><div><h3>Podaci poreznog obveznika / obrta</h3><p>Koriste se u zaglavljima PDF poslovnih knjiga.</p></div></div><article class="panel"><form id="profileForm" class="profile-grid"><label>Ime i prezime vlasnika<input name="ownerName" value="${esc(p.ownerName)}"></label><label>Naziv radnje / obrta<input name="businessName" value="${esc(p.businessName)}" required></label><label>JMB vlasnika<input name="jmb" value="${esc(p.jmb)}"></label><label>JIB / identifikacioni broj<input name="jib" value="${esc(p.jib)}"></label><label class="wide3">Adresa sjedišta<input name="address" value="${esc(p.address)}"></label><label>Oznaka / naziv osnovne djelatnosti<input name="activity" value="${esc(p.activity)}"></label><label>PDV status<select name="vatRegistered"><option value="false" ${!p.vatRegistered?'selected':''}>Nije PDV obveznik</option><option value="true" ${p.vatRegistered?'selected':''}>PDV obveznik</option></select></label><label>PDV broj<input name="vatNumber" value="${esc(p.vatNumber)}"></label><div class="form-actions wide3"><button class="primary-btn">Sačuvaj podatke obrta</button></div></form></article>`;
    $('#profileForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);db.profile={ownerName:f.get('ownerName'),businessName:f.get('businessName'),jmb:f.get('jmb'),jib:f.get('jib'),address:f.get('address'),activity:f.get('activity'),vatRegistered:f.get('vatRegistered')==='true',vatNumber:f.get('vatNumber')};save();alert('Podaci obrta su sačuvani.');};
    $('#addKpBtn').onclick=()=>modal('Novi unos KP‑1042',`<form class="form-grid"><label>Datum<input type="date" name="date" value="${today()}" required></label><label>Broj dokumenta<input name="doc" required></label><label class="wide">Opis dokumenta<input name="desc" required></label><label>Gotovina (KM)<input type="number" name="cash" step="0.01" value="0"></label><label>Bezgotovinski (KM)<input type="number" name="bank" step="0.01" value="0"></label><div class="form-actions wide"><button class="primary-btn">Sačuvaj</button></div></form>`,f=>{db.kp.push({id:uid(),date:f.get('date'),doc:f.get('doc'),desc:f.get('desc'),cash:Number(f.get('cash')||0),bank:Number(f.get('bank')||0)});save();});
    $('#addAssetBtn').onclick=()=>modal('Dugotrajna imovina PLDI‑1043',`<form class="form-grid"><label class="wide">Naziv stvari / prava<input name="name" required></label><label>Datum nabavke<input type="date" name="date" value="${today()}" required></label><label>Broj dokumenta<input name="doc" required></label><label>Nabavna vrijednost<input type="number" name="cost" step="0.01" required></label><label>Knjigovodstvena vrijednost<input type="number" name="bookValue" step="0.01" required></label><label>Vijek trajanja (god.)<input type="number" name="life" step="0.1" required></label><label>Stopa amortizacije (%)<input type="number" name="rate" step="0.01" required></label><label>Otpis za period (KM)<input type="number" name="depr" step="0.01" value="0" required></label><div class="form-actions wide"><button class="primary-btn">Sačuvaj</button></div></form>`,f=>{db.assets.push({id:uid(),name:f.get('name'),date:f.get('date'),doc:f.get('doc'),cost:Number(f.get('cost')),bookValue:Number(f.get('bookValue')),life:f.get('life'),rate:Number(f.get('rate')),depr:Number(f.get('depr'))});save();});
    $('#addEpoBtn').onclick=()=>modal('EPO‑1044',`<form class="form-grid"><label>Vrsta<select name="type"><option value="receivable">Potraživanje (izdati račun)</option><option value="payable">Obaveza (primljeni račun)</option></select></label><label>Kupac / dobavljač<input name="party" required></label><label>Broj računa<input name="invoiceNo" required></label><label>Datum računa<input type="date" name="invoiceDate" value="${today()}" required></label><label>Iznos računa<input type="number" name="amount" step="0.01" required></label><label>Datum naplate / uplate<input type="date" name="paidDate"></label><label>Naplaćeno / uplaćeno<input type="number" name="paidAmount" step="0.01" value="0"></label><label>R.br. u KPR<input name="kprNo"></label><div class="form-actions wide"><button class="primary-btn">Sačuvaj</button></div></form>`,f=>{db.epo.push({id:uid(),type:f.get('type'),party:f.get('party'),invoiceNo:f.get('invoiceNo'),invoiceDate:f.get('invoiceDate'),amount:Number(f.get('amount')),paidDate:f.get('paidDate'),paidAmount:Number(f.get('paidAmount')||0),kprNo:f.get('kprNo')});save();});
    $$('[data-pdf]').forEach(b=>b.onclick=()=>exportBookPdf(b.dataset.pdf));
  }
  window.delBook=(type,id)=>{if(confirm('Obrisati unos?')){db[type]=db[type].filter(x=>x.id!==id);save();}};

  // ---------- better client render ----------
  function renderClientCards(){ const grid=$('#clientGrid'); if(!grid)return; grid.innerHTML=db.clients.length?db.clients.map(c=>`<article class="client-card"><div class="client-card-top"><div style="display:flex;gap:11px"><div class="avatar">${esc((c.name||'?')[0])}</div><div><h4>${esc(c.name)}</h4><p>${esc(c.contact||c.email||c.phone||'Klijent')}</p></div></div></div><div style="margin-top:12px;font-size:12px;line-height:1.6;color:#64748b">${c.idNumber?`JIB: <b>${esc(c.idNumber)}</b><br>`:''}${c.vatNumber?`PDV: ${esc(c.vatNumber)}<br>`:''}${c.address?esc(c.address):''}</div></article>`).join(''):'<div class="book-empty">Nema klijenata.</div>'; }

  // ---------- PDF engine ----------
  let pdfPromise=null;
  function loadScript(src){return new Promise((resolve,reject)=>{const s=document.createElement('script');s.src=src;s.onload=resolve;s.onerror=reject;document.head.appendChild(s);});}
  async function ensurePdf(){if(!pdfPromise)pdfPromise=(async()=>{if(!window.jspdf)await loadScript('https://cdn.jsdelivr.net/npm/jspdf@2.5.2/dist/jspdf.umd.min.js');if(!window.jspdf.jsPDF.API.autoTable)await loadScript('https://cdn.jsdelivr.net/npm/jspdf-autotable@3.8.4/dist/jspdf.plugin.autotable.min.js');})();return pdfPromise;}
  function pdfHeader(doc,title,code,orientation){const p=db.profile, w=doc.internal.pageSize.getWidth();doc.setFontSize(13);doc.text(title,14,14);doc.setFontSize(8);doc.text(`Obrazac ${code}`,w-14,14,{align:'right'});doc.setFontSize(8);doc.text(`${p.ownerName||'Vlasnik nije unesen'} · ${p.businessName||'ALLUR'} · JIB: ${p.jib||'—'} · ${p.address||'—'}`,14,20);doc.text(`Porezni period: ${new Date().getFullYear()}.`,14,25);}
  async function exportBookPdf(code){try{await ensurePdf();const {jsPDF}=window.jspdf;let doc=new jsPDF({orientation:'landscape',unit:'mm',format:'a4'});let head=[],body=[],title='',file='';
    if(code==='kpr'){const r=kprRows();title='KNJIGA PRIHODA I RASHODA';file='KPR-1041-Allur.pdf';head=[['7 R.br.','8 Datum','9 Dokument','10 Opis','11 Gotovina','12 Trans. račun','13 Drugo','14 PDV prihod','15 Ukupni prihod','16 Roba/materijal','17 Bruto plaće','18 Doprinosi','19 Ostali rashodi','20 PDV rashod','21 Ukupni rashodi']];body=r.map(x=>[x.no,x.date,x.doc,x.desc,x.cash||'',x.bank||'',x.otherIn||'',x.inVat||'',x.totalIncome||'',x.material||'',x.wages||'',x.contrib||'',x.otherExp||'',x.outVat||'',x.totalExpense||'']);}
    if(code==='kp'){title='KNJIGA PROMETA';file='KP-1042-Allur.pdf';head=[['8 R.br.','9 Datum','10 Dokument','11 Opis','12 Gotovina','13 Bezgotovinski','14 Ukupno']];body=(db.kp||[]).map((x,i)=>[i+1,x.date,x.doc,x.desc,x.cash,x.bank,Number(x.cash)+Number(x.bank)]);}
    if(code==='pldi'){title='POPISNA LISTA DUGOTRAJNE IMOVINE';file='PLDI-1043-Allur.pdf';head=[['8 R.br.','9 Naziv','10 Datum','11 Dokument','12 Nabavna vrijed.','13 Knjigov. vrijed.','14 Vijek','15 Stopa %','16 Otpis','17 Vrijed. kraj']];body=(db.assets||[]).map((x,i)=>[i+1,x.name,x.date,x.doc,x.cost,x.bookValue,x.life,x.rate,x.depr,Math.max(0,x.bookValue-x.depr)]);}
    if(code==='epo'){title='EVIDENCIJA POTRAŽIVANJA I OBAVEZA';file='EPO-1044-Allur.pdf';head=[['7 R.br.','8 Kupac/dobavljač','Vrsta','Broj računa','Datum','Iznos','Datum naplate/uplate','Naplaćeno/uplaćeno','19 R.br. KPR']];body=(db.epo||[]).map((x,i)=>[i+1,x.party,x.type==='receivable'?'Potraživanje':'Obaveza',x.invoiceNo,x.invoiceDate,x.amount,x.paidDate||'',x.paidAmount||0,x.kprNo||'']);}
    pdfHeader(doc,title,code.toUpperCase()+'-'+({kpr:'1041',kp:'1042',pldi:'1043',epo:'1044'}[code]||''));doc.autoTable({startY:30,head,body,theme:'grid',styles:{fontSize:6,cellPadding:1.2,overflow:'linebreak'},headStyles:{fontStyle:'bold'},didDrawPage:(data)=>{const n=doc.internal.getNumberOfPages();doc.setFontSize(7);doc.text(`Allur Business · Stranica ${data.pageNumber}`,doc.internal.pageSize.getWidth()-14,doc.internal.pageSize.getHeight()-7,{align:'right'});}});doc.save(file);
  }catch(e){console.error(e);alert('PDF biblioteka se nije mogla učitati. Provjeri internet vezu i pokušaj ponovo.');}}
  window.exportBookPdf=exportBookPdf;

  // ---------- wrap base render ----------
  const baseRender=render;
  render=function(){baseRender();renderBooks();renderClientCards();};
  // override old navigation listener issue by re-bind all
  $$('.nav-item').forEach(b=>b.onclick=()=>showPage(b.dataset.page));
  render();
})();
